# Generated by Django 5.1.4 on 2025-05-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
